name: test-deployment
version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3060:3060"
    networks:
      - automation_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports: 
      - "8080:80"
    networks:
      - automation_net
    
networks:
  automation_net:
    external: true
